export const routes = {
  home: "/",
  dashboard: "/dashboard",
  profile: "/dashboard/profile",
  editProfile: "/dashboard/profile/edit",
  changePassword: "/dashboard/change-password",
  settings: "/dashboard/settings",
  helpSupport: "/dashboard/help-support",
  land: "/dashboard/my-land",
  dashboardExplore: "/dashboard/explore",
  purchases: "/dashboard/purchases",
  certificates: "/dashboard/certificates",
  cart: "/dashboard/cart",
  explore: "/explore",
  blog: "/blog",
  contact: "/contact",
  login: "/login",
  signup: "/signup",
  privacy: "/privacy",
  terms: "/terms",
  dashboardPrivacy: "/dashboard/privacy",
  dashboardTerms: "/dashboard/terms",
} as const;

export type AppRoute = (typeof routes)[keyof typeof routes];
