"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type DashboardLanguage = "EN" | "PL" | "TH";

const translations: Record<string, Record<Exclude<DashboardLanguage, "EN">, string>> = {
  Home: { PL: "Strona gÅ‚Ã³wna", TH: "à¸«à¸™à¹‰à¸²à¸«à¸¥à¸±à¸" },
  "Explore Map": { PL: "Eksploruj mapÄ™", TH: "à¸ªà¸³à¸£à¸§à¸ˆà¹à¸œà¸™à¸—à¸µà¹ˆ" },
  "My Land": { PL: "Moja ziemia", TH: "à¸—à¸µà¹ˆà¸”à¸´à¸™à¸‚à¸­à¸‡à¸‰à¸±à¸™" },
  English: { PL: "Angielski", TH: "à¸­à¸±à¸‡à¸à¸¤à¸©" },
  Polish: { PL: "Polski", TH: "à¹‚à¸›à¹à¸¥à¸™à¸”à¹Œ" },
  Thai: { PL: "Tajski", TH: "à¹„à¸—à¸¢" },
  Profile: { PL: "Profil", TH: "à¹‚à¸›à¸£à¹„à¸Ÿà¸¥à¹Œ" },
  "Change Password": { PL: "ZmieÅ„ hasÅ‚o", TH: "à¹€à¸›à¸¥à¸µà¹ˆà¸¢à¸™à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™" },
  "My Purchases": { PL: "Moje zakupy", TH: "à¸à¸²à¸£à¸‹à¸·à¹‰à¸­à¸‚à¸­à¸‡à¸‰à¸±à¸™" },
  "My Certificates": { PL: "Moje certyfikaty", TH: "à¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡à¸‚à¸­à¸‡à¸‰à¸±à¸™" },
  Certificates: { PL: "Certyfikaty", TH: "à¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡" },
  Gifted: { PL: "Podarowane", TH: "à¸‚à¸­à¸‡à¸‚à¸§à¸±à¸" },
  Settings: { PL: "Ustawienia", TH: "à¸à¸²à¸£à¸•à¸±à¹‰à¸‡à¸„à¹ˆà¸²" },
  "Help & Support": { PL: "Pomoc i wsparcie", TH: "à¸Šà¹ˆà¸§à¸¢à¹€à¸«à¸¥à¸·à¸­à¹à¸¥à¸°à¸ªà¸™à¸±à¸šà¸ªà¸™à¸¸à¸™" },
  "Term & Condition": { PL: "Warunki", TH: "à¸‚à¹‰à¸­à¸à¸³à¸«à¸™à¸”à¹à¸¥à¸°à¹€à¸‡à¸·à¹ˆà¸­à¸™à¹„à¸‚" },
  "Terms and Conditions": { PL: "Warunki", TH: "à¸‚à¹‰à¸­à¸à¸³à¸«à¸™à¸”à¹à¸¥à¸°à¹€à¸‡à¸·à¹ˆà¸­à¸™à¹„à¸‚" },
  "Privacy Policy": { PL: "Polityka prywatnoÅ›ci", TH: "à¸™à¹‚à¸¢à¸šà¸²à¸¢à¸„à¸§à¸²à¸¡à¹€à¸›à¹‡à¸™à¸ªà¹ˆà¸§à¸™à¸•à¸±à¸§" },
  "Account Menu": { PL: "Menu konta", TH: "à¹€à¸¡à¸™à¸¹à¸šà¸±à¸à¸Šà¸µ" },
  Logout: { PL: "Wyloguj", TH: "à¸­à¸­à¸à¸ˆà¸²à¸à¸£à¸°à¸šà¸š" },
  Cart: { PL: "Koszyk", TH: "à¸£à¸–à¹€à¸‚à¹‡à¸™" },
  "My Profile": { PL: "MÃ³j profil", TH: "à¹‚à¸›à¸£à¹„à¸Ÿà¸¥à¹Œà¸‚à¸­à¸‡à¸‰à¸±à¸™" },
  "All Purchases": { PL: "Wszystkie zakupy", TH: "à¸à¸²à¸£à¸‹à¸·à¹‰à¸­à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”" },
  "View your plots and purchase details in one place.": {
    PL: "Zobacz swoje dziaÅ‚ki i szczegÃ³Å‚y zakupÃ³w w jednym miejscu.",
    TH: "à¸”à¸¹à¹à¸›à¸¥à¸‡à¸—à¸µà¹ˆà¸”à¸´à¸™à¹à¸¥à¸°à¸£à¸²à¸¢à¸¥à¸°à¹€à¸­à¸µà¸¢à¸”à¸à¸²à¸£à¸‹à¸·à¹‰à¸­à¸‚à¸­à¸‡à¸„à¸¸à¸“à¹ƒà¸™à¸—à¸µà¹ˆà¹€à¸”à¸µà¸¢à¸§",
  },
  Location: { PL: "Lokalizacja", TH: "à¸ªà¸–à¸²à¸™à¸—à¸µà¹ˆ" },
  Purchased: { PL: "Zakupiono", TH: "à¸‹à¸·à¹‰à¸­à¹€à¸¡à¸·à¹ˆà¸­" },
  "LAND SIZE:": { PL: "POWIERZCHNIA:", TH: "à¸‚à¸™à¸²à¸”à¸—à¸µà¹ˆà¸”à¸´à¸™:" },
  "LOCATION:": { PL: "LOKALIZACJA:", TH: "à¸ªà¸–à¸²à¸™à¸—à¸µà¹ˆ:" },
  Amount: { PL: "Kwota", TH: "à¸ˆà¸³à¸™à¸§à¸™à¹€à¸‡à¸´à¸™" },
  Rai: { PL: "Rai", TH: "à¹„à¸£à¹ˆ" },
  "Loading purchases...": { PL: "Åadowanie zakupÃ³w...", TH: "à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”à¸à¸²à¸£à¸‹à¸·à¹‰à¸­..." },
  "All Certificates": { PL: "Wszystkie certyfikaty", TH: "à¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”" },
  "View and download your land ownership certificates.": {
    PL: "PrzeglÄ…daj i pobieraj certyfikaty wÅ‚asnoÅ›ci dziaÅ‚ek.",
    TH: "à¸”à¸¹à¹à¸¥à¸°à¸”à¸²à¸§à¸™à¹Œà¹‚à¸«à¸¥à¸”à¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡à¸à¸£à¸£à¸¡à¸ªà¸´à¸—à¸˜à¸´à¹Œà¸—à¸µà¹ˆà¸”à¸´à¸™à¸‚à¸­à¸‡à¸„à¸¸à¸“",
  },
  "Generated on": { PL: "Wygenerowano", TH: "à¸ªà¸£à¹‰à¸²à¸‡à¹€à¸¡à¸·à¹ˆà¸­" },
  "View â†’": { PL: "Zobacz â†’", TH: "à¸”à¸¹ â†’" },
  "Loading certificates...": { PL: "Åadowanie certyfikatÃ³w...", TH: "à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”à¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡..." },
  Filter: { PL: "Filtruj", TH: "à¸à¸£à¸­à¸‡" },
  Sort: { PL: "Sortuj", TH: "à¹€à¸£à¸µà¸¢à¸‡à¸¥à¸³à¸”à¸±à¸š" },
  Apply: { PL: "Zastosuj", TH: "à¹ƒà¸Šà¹‰" },
  Reset: { PL: "Resetuj", TH: "à¸£à¸µà¹€à¸‹à¹‡à¸•" },
  "Clear All": { PL: "WyczyÅ›Ä‡ wszystko", TH: "à¸¥à¹‰à¸²à¸‡à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”" },
  "Sort by": { PL: "Sortuj wedÅ‚ug", TH: "à¹€à¸£à¸µà¸¢à¸‡à¸•à¸²à¸¡" },
  "Reorder active parcel markers": { PL: "ZmieÅ„ kolejnoÅ›Ä‡ aktywnych dziaÅ‚ek", TH: "à¸ˆà¸±à¸”à¸¥à¸³à¸”à¸±à¸šà¹à¸›à¸¥à¸‡à¸—à¸µà¹ˆà¹ƒà¸Šà¹‰à¸‡à¸²à¸™à¸­à¸¢à¸¹à¹ˆà¹ƒà¸«à¸¡à¹ˆ" },
  Recommended: { PL: "Polecane", TH: "à¹à¸™à¸°à¸™à¸³" },
  "Curated by premier parcel score": { PL: "Wybrane wedÅ‚ug oceny dziaÅ‚ki", TH: "à¸„à¸±à¸”à¸ªà¸£à¸£à¸•à¸²à¸¡à¸„à¸°à¹à¸™à¸™à¹à¸›à¸¥à¸‡à¸Šà¸±à¹‰à¸™à¸™à¸³" },
  "Price: Low to High": { PL: "Cena: od najniÅ¼szej", TH: "à¸£à¸²à¸„à¸²: à¸•à¹ˆà¸³à¹„à¸›à¸ªà¸¹à¸‡" },
  "Price: High to Low": { PL: "Cena: od najwyÅ¼szej", TH: "à¸£à¸²à¸„à¸²: à¸ªà¸¹à¸‡à¹„à¸›à¸•à¹ˆà¸³" },
  "Land Area: Small to Large": { PL: "Powierzchnia: od najmniejszej", TH: "à¸‚à¸™à¸²à¸”à¸—à¸µà¹ˆà¸”à¸´à¸™: à¹€à¸¥à¹‡à¸à¹„à¸›à¹ƒà¸«à¸à¹ˆ" },
  "Land Area: Large to Small": { PL: "Powierzchnia: od najwiÄ™kszej", TH: "à¸‚à¸™à¸²à¸”à¸—à¸µà¹ˆà¸”à¸´à¸™: à¹ƒà¸«à¸à¹ˆà¹„à¸›à¹€à¸¥à¹‡à¸" },
  "Newest Added": { PL: "Ostatnio dodane", TH: "à¹€à¸žà¸´à¹ˆà¸¡à¸¥à¹ˆà¸²à¸ªà¸¸à¸”" },
  DEFAULT: { PL: "DOMYÅšLNE", TH: "à¸„à¹ˆà¸²à¹€à¸£à¸´à¹ˆà¸¡à¸•à¹‰à¸™" },
  Recent: { PL: "Ostatnie", TH: "à¸¥à¹ˆà¸²à¸ªà¸¸à¸”" },
  "Filter Plots": { PL: "Filtruj dziaÅ‚ki", TH: "à¸à¸£à¸­à¸‡à¹à¸›à¸¥à¸‡à¸—à¸µà¹ˆà¸”à¸´à¸™" },
  "Narrow 1,168 parcels across Thailand": { PL: "ZawÄ™Åº 1 168 dziaÅ‚ek w Tajlandii", TH: "à¸à¸£à¸­à¸‡ 1,168 à¹à¸›à¸¥à¸‡à¸—à¸±à¹ˆà¸§à¸›à¸£à¸°à¹€à¸—à¸¨à¹„à¸—à¸¢" },
  "Zone Category": { PL: "Kategoria strefy", TH: "à¸«à¸¡à¸§à¸”à¸«à¸¡à¸¹à¹ˆà¹‚à¸‹à¸™" },
  "All Zones": { PL: "Wszystkie strefy", TH: "à¸—à¸¸à¸à¹‚à¸‹à¸™" },
  Popular: { PL: "Popularne", TH: "à¸¢à¸­à¸”à¸™à¸´à¸¢à¸¡" },
  Standard: { PL: "Standard", TH: "à¸¡à¸²à¸•à¸£à¸à¸²à¸™" },
  "Gifted Plots": { PL: "DziaÅ‚ki podarowane", TH: "à¹à¸›à¸¥à¸‡à¸‚à¸­à¸‡à¸‚à¸§à¸±à¸" },
  "Land Area (Rai)": { PL: "Powierzchnia (Rai)", TH: "à¸‚à¸™à¸²à¸”à¸—à¸µà¹ˆà¸”à¸´à¸™ (à¹„à¸£à¹ˆ)" },
  "1 Rai = 1,600 mÂ²": { PL: "1 Rai = 1 600 mÂ²", TH: "1 à¹„à¸£à¹ˆ = 1,600 à¸•à¸£.à¸¡." },
  "Price Range (USD)": { PL: "Zakres cen (USD)", TH: "à¸Šà¹ˆà¸§à¸‡à¸£à¸²à¸„à¸² (USD)" },
  "$100 â€“ $2,500": { PL: "$100 â€“ $2,500", TH: "$100 â€“ $2,500" },
  "Apply Filters": { PL: "Zastosuj filtry", TH: "à¹ƒà¸Šà¹‰à¸•à¸±à¸§à¸à¸£à¸­à¸‡" },
  "plots found": { PL: "znalezionych dziaÅ‚ek", TH: "à¹à¸›à¸¥à¸‡à¸—à¸µà¹ˆà¸žà¸š" },
  Search: { PL: "Szukaj", TH: "à¸„à¹‰à¸™à¸«à¸²" },
  "View Details": { PL: "Zobacz szczegÃ³Å‚y", TH: "à¸”à¸¹à¸£à¸²à¸¢à¸¥à¸°à¹€à¸­à¸µà¸¢à¸”" },
  "View Map": { PL: "Zobacz mapÄ™", TH: "à¸”à¸¹à¹à¸œà¸™à¸—à¸µà¹ˆ" },
  "View Certificate": { PL: "Zobacz certyfikat", TH: "à¸”à¸¹à¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡" },
  Download: { PL: "Pobierz", TH: "à¸”à¸²à¸§à¸™à¹Œà¹‚à¸«à¸¥à¸”" },
  Share: { PL: "UdostÄ™pnij", TH: "à¹à¸Šà¸£à¹Œ" },
  Close: { PL: "Zamknij", TH: "à¸›à¸´à¸”" },
  Cancel: { PL: "Anuluj", TH: "à¸¢à¸à¹€à¸¥à¸´à¸" },
  Save: { PL: "Zapisz", TH: "à¸šà¸±à¸™à¸—à¸¶à¸" },
  Edit: { PL: "Edytuj", TH: "à¹à¸à¹‰à¹„à¸‚" },
  "Back to Dashboard": { PL: "PowrÃ³t do panelu", TH: "à¸à¸¥à¸±à¸šà¹„à¸›à¸—à¸µà¹ˆà¹à¸”à¸Šà¸šà¸­à¸£à¹Œà¸”" },
  "Back to Cart": { PL: "PowrÃ³t do koszyka", TH: "à¸à¸¥à¸±à¸šà¹„à¸›à¸—à¸µà¹ˆà¸£à¸–à¹€à¸‚à¹‡à¸™" },
  "Back to Purchases": { PL: "PowrÃ³t do zakupÃ³w", TH: "à¸à¸¥à¸±à¸šà¹„à¸›à¸—à¸µà¹ˆà¸à¸²à¸£à¸‹à¸·à¹‰à¸­" },
  "Explore on Map â†’": { PL: "Eksploruj na mapie â†’", TH: "à¸ªà¸³à¸£à¸§à¸ˆà¸šà¸™à¹à¸œà¸™à¸—à¸µà¹ˆ â†’" },
  "Discount Â· TAJ10": { PL: "Rabat Â· TAJ10", TH: "à¸ªà¹ˆà¸§à¸™à¸¥à¸” Â· TAJ10" },
  "Payment fully settled": { PL: "PÅ‚atnoÅ›Ä‡ w peÅ‚ni rozliczona", TH: "à¸Šà¸³à¸£à¸°à¹€à¸‡à¸´à¸™à¸„à¸£à¸šà¹à¸¥à¹‰à¸§" },
  "Loading order...": { PL: "Åadowanie zamÃ³wienia...", TH: "à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”à¸„à¸³à¸ªà¸±à¹ˆà¸‡à¸‹à¸·à¹‰à¸­..." },
  "Back to My Certificates": { PL: "PowrÃ³t do certyfikatÃ³w", TH: "à¸à¸¥à¸±à¸šà¹„à¸›à¸—à¸µà¹ˆà¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡" },
  "Total Owned": { PL: "ÅÄ…cznie posiadane", TH: "à¸—à¸µà¹ˆà¸”à¸´à¸™à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”" },
  "Total Spent": { PL: "ÅÄ…cznie wydano", TH: "à¸¢à¸­à¸”à¹ƒà¸Šà¹‰à¸ˆà¹ˆà¸²à¸¢à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”" },
  Regions: { PL: "Regiony", TH: "à¸ à¸¹à¸¡à¸´à¸ à¸²à¸„" },
  "Order Summary": { PL: "Podsumowanie zamÃ³wienia", TH: "à¸ªà¸£à¸¸à¸›à¸„à¸³à¸ªà¸±à¹ˆà¸‡à¸‹à¸·à¹‰à¸­" },
  "Payment Information": { PL: "Informacje o pÅ‚atnoÅ›ci", TH: "à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸à¸²à¸£à¸Šà¸³à¸£à¸°à¹€à¸‡à¸´à¸™" },
  Completed: { PL: "ZakoÅ„czone", TH: "à¹€à¸ªà¸£à¹‡à¸ˆà¸ªà¸´à¹‰à¸™" },
  Pending: { PL: "OczekujÄ…ce", TH: "à¸£à¸­à¸”à¸³à¹€à¸™à¸´à¸™à¸à¸²à¸£" },
  Available: { PL: "DostÄ™pne", TH: "à¸žà¸£à¹‰à¸­à¸¡à¹ƒà¸Šà¹‰à¸‡à¸²à¸™" },
  "No purchases match the selected filters.": {
    PL: "Å»adne zakupy nie pasujÄ… do wybranych filtrÃ³w.",
    TH: "à¹„à¸¡à¹ˆà¸¡à¸µà¸à¸²à¸£à¸‹à¸·à¹‰à¸­à¸—à¸µà¹ˆà¸•à¸£à¸‡à¸à¸±à¸šà¸•à¸±à¸§à¸à¸£à¸­à¸‡à¸—à¸µà¹ˆà¹€à¸¥à¸·à¸­à¸",
  },
  "No certificates match the selected filters.": {
    PL: "Å»adne certyfikaty nie pasujÄ… do wybranych filtrÃ³w.",
    TH: "à¹„à¸¡à¹ˆà¸¡à¸µà¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡à¸—à¸µà¹ˆà¸•à¸£à¸‡à¸à¸±à¸šà¸•à¸±à¸§à¸à¸£à¸­à¸‡à¸—à¸µà¹ˆà¹€à¸¥à¸·à¸­à¸",
  },
  "Your collection of places across Thailand., all in one place.": {
    PL: "Twoja kolekcja miejsc w Tajlandii w jednym miejscu.",
    TH: "à¸„à¸­à¸¥à¹€à¸¥à¸à¸Šà¸±à¸™à¸ªà¸–à¸²à¸™à¸—à¸µà¹ˆà¸‚à¸­à¸‡à¸„à¸¸à¸“à¸—à¸±à¹ˆà¸§à¸›à¸£à¸°à¹€à¸—à¸¨à¹„à¸—à¸¢à¹ƒà¸™à¸—à¸µà¹ˆà¹€à¸”à¸µà¸¢à¸§",
  },
  "Explore Thailand": { PL: "Odkrywaj TajlandiÄ™", TH: "à¸ªà¸³à¸£à¸§à¸ˆà¸›à¸£à¸°à¹€à¸—à¸¨à¹„à¸—à¸¢" },
  "Give a Little Piece of Thailand": {
    PL: "Podaruj kawaÅ‚ek Tajlandii",
    TH: "à¸¡à¸­à¸šà¸Šà¸´à¹‰à¸™à¸ªà¹ˆà¸§à¸™à¹€à¸¥à¹‡à¸à¹† à¸‚à¸­à¸‡à¸›à¸£à¸°à¹€à¸—à¸¨à¹„à¸—à¸¢",
  },
  "Gift a plot": { PL: "Podaruj dziaÅ‚kÄ™", TH: "à¸¡à¸­à¸šà¹à¸›à¸¥à¸‡à¸—à¸µà¹ˆà¸”à¸´à¸™" },
  "Information We Collect": {
    PL: "Informacje, ktÃ³re zbieramy",
    TH: "à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸—à¸µà¹ˆà¹€à¸£à¸²à¹€à¸à¹‡à¸šà¸£à¸§à¸šà¸£à¸§à¸¡",
  },
  "How We Use Your Information": {
    PL: "Jak wykorzystujemy Twoje informacje",
    TH: "à¹€à¸£à¸²à¹ƒà¸Šà¹‰à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸‚à¸­à¸‡à¸„à¸¸à¸“à¸­à¸¢à¹ˆà¸²à¸‡à¹„à¸£",
  },
  "Table of Contents": { PL: "Spis treÅ›ci", TH: "à¸ªà¸²à¸£à¸šà¸±à¸" },
  Contents: { PL: "Spis treÅ›ci", TH: "à¸ªà¸²à¸£à¸šà¸±à¸" },
  "Know the rules and terms of using Tajlandia.": { PL: "Poznaj zasady i warunki korzystania z Tajlandia.", TH: "à¹€à¸£à¸µà¸¢à¸™à¸£à¸¹à¹‰à¸à¸Žà¹à¸¥à¸°à¹€à¸‡à¸·à¹ˆà¸­à¸™à¹„à¸‚à¸à¸²à¸£à¹ƒà¸Šà¹‰ Tajlandia" },
  "Learn how we protect and use your information.": { PL: "Dowiedz siÄ™, jak chronimy i wykorzystujemy Twoje informacje.", TH: "à¹€à¸£à¸µà¸¢à¸™à¸£à¸¹à¹‰à¸§à¸´à¸˜à¸µà¸—à¸µà¹ˆà¹€à¸£à¸²à¸›à¸à¸›à¹‰à¸­à¸‡à¹à¸¥à¸°à¹ƒà¸Šà¹‰à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸‚à¸­à¸‡à¸„à¸¸à¸“" },
  "Legal Documentation": { PL: "Dokumentacja prawna", TH: "à¹€à¸­à¸à¸ªà¸²à¸£à¸—à¸²à¸‡à¸à¸Žà¸«à¸¡à¸²à¸¢" },
  Sections: { PL: "Sekcje", TH: "à¸ªà¹ˆà¸§à¸™" },
  Language: { PL: "JÄ™zyk", TH: "à¸ à¸²à¸©à¸²" },
  "Open dashboard menu": { PL: "OtwÃ³rz menu panelu", TH: "à¹€à¸›à¸´à¸”à¹€à¸¡à¸™à¸¹à¹à¸”à¸Šà¸šà¸­à¸£à¹Œà¸”" },
  "Loading dashboard...": { PL: "Åadowanie panelu...", TH: "à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”à¹à¸”à¸Šà¸šà¸­à¸£à¹Œà¸”..." },
  "Loading map...": { PL: "Åadowanie mapy...", TH: "à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”à¹à¸œà¸™à¸—à¸µà¹ˆ..." },
  "Loading profile...": { PL: "Åadowanie profilu...", TH: "à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”à¹‚à¸›à¸£à¹„à¸Ÿlu..." },
  "Loading support...": { PL: "Åadowanie pomocy...", TH: "à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”à¸à¸²à¸£à¸Šà¹ˆà¸§à¸¢à¹€à¸«à¸¥à¸·à¸­..." },
  "Loading settings...": { PL: "Åadowanie ustawieÅ„...", TH: "à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”à¸à¸²à¸£à¸•à¸±à¹‰à¸‡à¸„à¹ˆà¸²..." },
  "Your Tajlandia Home": { PL: "TwÃ³j dom Tajlandia", TH: "à¸šà¹‰à¸²à¸™ Tajlandia à¸‚à¸­à¸‡à¸„à¸¸à¸“" },
  "Welcome back,": { PL: "Witaj ponownie,", TH: "à¸¢à¸´à¸™à¸”à¸µà¸•à¹‰à¸­à¸™à¸£à¸±à¸šà¸à¸¥à¸±à¸šà¸¡à¸²," },
  "Hereâ€™s everything you own in Thailand.": { PL: "Oto wszystko, co posiadasz w Tajlandii.", TH: "à¸™à¸µà¹ˆà¸„à¸·à¸­à¸—à¸¸à¸à¸ªà¸´à¹ˆà¸‡à¸—à¸µà¹ˆà¸„à¸¸à¸“à¹€à¸›à¹‡à¸™à¹€à¸ˆà¹‰à¸²à¸‚à¸­à¸‡à¹ƒà¸™à¸›à¸£à¸°à¹€à¸—à¸¨à¹„à¸—à¸¢" },
  "Explore Thailand â†’": { PL: "Odkrywaj TajlandiÄ™ â†’", TH: "à¸ªà¸³à¸£à¸§à¸ˆà¸›à¸£à¸°à¹€à¸—à¸¨à¹„à¸—à¸¢ â†’" },
  "Ownership Overview": { PL: "PrzeglÄ…d wÅ‚asnoÅ›ci", TH: "à¸ à¸²à¸žà¸£à¸§à¸¡à¸„à¸§à¸²à¸¡à¹€à¸›à¹‡à¸™à¹€à¸ˆà¹‰à¸²à¸‚à¸­à¸‡" },
  "Your Collection": { PL: "Twoja kolekcja", TH: "à¸„à¸­à¸¥à¹€à¸¥à¸à¸Šà¸±à¸™à¸‚à¸­à¸‡à¸„à¸¸à¸“" },
  "All holdings verified across Thailand": { PL: "Wszystkie aktywa zweryfikowane w Tajlandii", TH: "à¸•à¸£à¸§à¸ˆà¸ªà¸­à¸šà¸—à¸£à¸±à¸žà¸¢à¹Œà¸ªà¸´à¸™à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”à¸—à¸±à¹ˆà¸§à¸›à¸£à¸°à¹€à¸—à¸¨à¹„à¸—à¸¢à¹à¸¥à¹‰à¸§" },
  "Total Land (Sq Rai)": { PL: "ÅÄ…czna ziemia (rai kw.)", TH: "à¸—à¸µà¹ˆà¸”à¸´à¸™à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸” (à¹„à¸£à¹ˆ à¸•à¸£.)" },
  "Total Land (5 Rai)": { PL: "ÅÄ…czna ziemia (5 rai)", TH: "à¸—à¸µà¹ˆà¸”à¸´à¸™à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸” (5 à¹„à¸£à¹ˆ)" },
  "Share a place worth remembering. Gift a Tajlandia plot to someone": {
    PL: "Podaruj miejsce warte zapamiÄ™tania. Podaruj dziaÅ‚kÄ™ Tajlandia",
    TH: "à¹à¸šà¹ˆà¸‡à¸›à¸±à¸™à¸ªà¸–à¸²à¸™à¸—à¸µà¹ˆà¸—à¸µà¹ˆà¸„à¸§à¸£à¸„à¹ˆà¸²à¹à¸à¹ˆà¸à¸²à¸£à¸ˆà¸”à¸ˆà¸³ à¸¡à¸­à¸šà¹à¸›à¸¥à¸‡ Tajlandia à¹ƒà¸«à¹‰à¸„à¸™à¸žà¸´à¹€à¸¨à¸©",
  },
  "special and let them build their own collection.": {
    PL: "bliskiej osobie i pozwÃ³l jej zbudowaÄ‡ wÅ‚asnÄ… kolekcjÄ™.",
    TH: "à¹à¸¥à¸°à¹ƒà¸«à¹‰à¸žà¸§à¸à¹€à¸‚à¸²à¸ªà¸£à¹‰à¸²à¸‡à¸„à¸­à¸¥à¹€à¸¥à¸à¸Šà¸±à¸™à¸‚à¸­à¸‡à¸•à¸™à¹€à¸­à¸‡",
  },
  "Plots Claimed": { PL: "ZajÄ™te dziaÅ‚ki", TH: "à¹à¸›à¸¥à¸‡à¸—à¸µà¹ˆà¸­à¹‰à¸²à¸‡à¸ªà¸´à¸—à¸˜à¸´à¹Œ" },
  "Your Land Archive": { PL: "Archiwum twojej ziemi", TH: "à¸„à¸¥à¸±à¸‡à¸—à¸µà¹ˆà¸”à¸´à¸™à¸‚à¸­à¸‡à¸„à¸¸à¸“" },
  "Share a place worth remembering. Gift a Tajlandia plot to someone special and let them build their own collection.": { PL: "Podaruj miejsce warte zapamiÄ™tania. Podaruj dziaÅ‚kÄ™ Tajlandia bliskiej osobie i pozwÃ³l jej zbudowaÄ‡ wÅ‚asnÄ… kolekcjÄ™.", TH: "à¹à¸šà¹ˆà¸‡à¸›à¸±à¸™à¸ªà¸–à¸²à¸™à¸—à¸µà¹ˆà¸—à¸µà¹ˆà¸„à¸§à¸£à¸„à¹ˆà¸²à¹à¸à¹ˆà¸à¸²à¸£à¸ˆà¸”à¸ˆà¸³ à¸¡à¸­à¸šà¹à¸›à¸¥à¸‡ Tajlandia à¹ƒà¸«à¹‰à¸„à¸™à¸žà¸´à¹€à¸¨à¸©à¹à¸¥à¸°à¹ƒà¸«à¹‰à¸žà¸§à¸à¹€à¸‚à¸²à¸ªà¸£à¹‰à¸²à¸‡à¸„à¸­à¸¥à¹€à¸¥à¸à¸Šà¸±à¸™à¸‚à¸­à¸‡à¸•à¸™à¹€à¸­à¸‡" },
  "Instant Digital Certificate": { PL: "Natychmiastowy certyfikat cyfrowy", TH: "à¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡à¸”à¸´à¸ˆà¸´à¸—à¸±à¸¥à¸—à¸±à¸™à¸—à¸µ" },
  "Official Cadastre Deed": { PL: "Oficjalny akt katastralny", TH: "à¹‚à¸‰à¸™à¸”à¸—à¸µà¹ˆà¸”à¸´à¸™à¸­à¸¢à¹ˆà¸²à¸‡à¹€à¸›à¹‡à¸™à¸—à¸²à¸‡à¸à¸²à¸£" },
  "Discover Plots â†’": { PL: "Odkryj dziaÅ‚ki â†’", TH: "à¸„à¹‰à¸™à¸«à¸²à¹à¸›à¸¥à¸‡à¸—à¸µà¹ˆà¸”à¸´à¸™ â†’" },
  "Island life, reimagined.": { PL: "Å»ycie na wyspie na nowo.", TH: "à¸Šà¸µà¸§à¸´à¸•à¸šà¸™à¹€à¸à¸²à¸°à¹ƒà¸™à¸¡à¸¸à¸¡à¸¡à¸­à¸‡à¹ƒà¸«à¸¡à¹ˆ" },
  "Where limestone meets the sea.": { PL: "Gdzie wapienne skaÅ‚y spotykajÄ… morze.", TH: "à¸—à¸µà¹ˆà¸‹à¸¶à¹ˆà¸‡à¸ à¸¹à¹€à¸‚à¸²à¸«à¸´à¸™à¸›à¸¹à¸™à¸žà¸šà¸à¸±à¸šà¸—à¸°à¹€à¸¥" },
  "Mountains, culture and quiet.": { PL: "GÃ³ry, kultura i spokÃ³j.", TH: "à¸ à¸¹à¹€à¸‚à¸² à¸§à¸±à¸’à¸™à¸˜à¸£à¸£à¸¡ à¹à¸¥à¸°à¸„à¸§à¸²à¸¡à¸ªà¸‡à¸š" },
  "Energy, culture and endless discovery.": { PL: "Energia, kultura i niekoÅ„czÄ…ce siÄ™ odkrycia.", TH: "à¸žà¸¥à¸±à¸‡ à¸§à¸±à¸’à¸™à¸˜à¸£à¸£à¸¡ à¹à¸¥à¸°à¸à¸²à¸£à¸„à¹‰à¸™à¸žà¸šà¹„à¸¡à¹ˆà¸£à¸¹à¹‰à¸ˆà¸š" },
  "Coastal escapes, just beyond the city.": { PL: "Nadmorski odpoczynek tuÅ¼ za miastem.", TH: "à¸Šà¸²à¸¢à¸à¸±à¹ˆà¸‡à¹à¸ªà¸™à¸ªà¸‡à¸šà¸—à¸µà¹ˆà¸­à¸¢à¸¹à¹ˆà¹„à¸¡à¹ˆà¹„à¸à¸¥à¸ˆà¸²à¸à¹€à¸¡à¸·à¸­à¸‡" },
  "Island serenity, beautifully preserved.": { PL: "PiÄ™knie zachowany spokÃ³j wyspy.", TH: "à¸„à¸§à¸²à¸¡à¸ªà¸‡à¸šà¸‚à¸­à¸‡à¹€à¸à¸²à¸°à¸—à¸µà¹ˆà¹„à¸”à¹‰à¸£à¸±à¸šà¸à¸²à¸£à¸”à¸¹à¹à¸¥à¸­à¸¢à¹ˆà¸²à¸‡à¸‡à¸”à¸‡à¸²à¸¡" },
  "Account Security": { PL: "BezpieczeÅ„stwo konta", TH: "à¸„à¸§à¸²à¸¡à¸›à¸¥à¸­à¸”à¸ à¸±à¸¢à¸‚à¸­à¸‡à¸šà¸±à¸à¸Šà¸µ" },
  "Authentication & Safeguards": { PL: "Uwierzytelnianie i zabezpieczenia", TH: "à¸à¸²à¸£à¸¢à¸·à¸™à¸¢à¸±à¸™à¸•à¸±à¸§à¸•à¸™à¹à¸¥à¸°à¸à¸²à¸£à¸›à¹‰à¸­à¸‡à¸à¸±à¸™" },
  "Interface & Chatbot Language": { PL: "JÄ™zyk interfejsu i chatbota", TH: "à¸ à¸²à¸©à¸²à¸‚à¸­à¸‡à¸­à¸´à¸™à¹€à¸—à¸­à¸£à¹Œà¹€à¸Ÿà¸‹à¹à¸¥à¸°à¹à¸Šà¸•à¸šà¸­à¸•" },
  "Interface & Change Language": { PL: "Interfejs i zmiana jÄ™zyka", TH: "à¸­à¸´à¸™à¹€à¸—à¸­à¸£à¹Œà¹€à¸Ÿà¸‹à¹à¸¥à¸°à¹€à¸›à¸¥à¸µà¹ˆà¸¢à¸™à¸ à¸²à¸©à¸²" },
  "English (Default - Global Cadastral)": { PL: "Angielski (domyÅ›lny - Global Cadastral)", TH: "à¸­à¸±à¸‡à¸à¸¤à¸© (à¸„à¹ˆà¸²à¹€à¸£à¸´à¹ˆà¸¡à¸•à¹‰à¸™ - Global Cadastral)" },
  "Language applies to land title dossiers, notifications, and cadastral maps.": { PL: "JÄ™zyk dotyczy dokumentacji wÅ‚asnoÅ›ci, powiadomieÅ„ i map katastralnych.", TH: "à¸ à¸²à¸©à¸²à¸™à¸µà¹‰à¹ƒà¸Šà¹‰à¸à¸±à¸šà¹€à¸­à¸à¸ªà¸²à¸£à¸ªà¸´à¸—à¸˜à¸´à¹Œà¸—à¸µà¹ˆà¸”à¸´à¸™ à¸à¸²à¸£à¹à¸ˆà¹‰à¸‡à¹€à¸•à¸·à¸­à¸™ à¹à¸¥à¸°à¹à¸œà¸™à¸—à¸µà¹ˆà¸—à¸µà¹ˆà¸”à¸´à¸™" },
  "Email notifications": { PL: "Powiadomienia e-mail", TH: "à¸à¸²à¸£à¹à¸ˆà¹‰à¸‡à¹€à¸•à¸·à¸­à¸™à¸—à¸²à¸‡à¸­à¸µà¹€à¸¡à¸¥" },
  "You'll receive important account and purchase updates by email.": { PL: "Otrzymasz waÅ¼ne aktualizacje konta i zakupÃ³w e-mailem.", TH: "à¸„à¸¸à¸“à¸ˆà¸°à¹„à¸”à¹‰à¸£à¸±à¸šà¸à¸²à¸£à¸­à¸±à¸›à¹€à¸”à¸•à¸šà¸±à¸à¸Šà¸µà¹à¸¥à¸°à¸à¸²à¸£à¸‹à¸·à¹‰à¸­à¸—à¸µà¹ˆà¸ªà¸³à¸„à¸±à¸à¸—à¸²à¸‡à¸­à¸µà¹€à¸¡à¸¥" },
  "Settings saved.": { PL: "Ustawienia zapisane.", TH: "à¸šà¸±à¸™à¸—à¸¶à¸à¸à¸²à¸£à¸•à¸±à¹‰à¸‡à¸„à¹ˆà¸²à¹à¸¥à¹‰à¸§" },
  "Update your account preferences and security details.": { PL: "Zaktualizuj preferencje konta i dane bezpieczeÅ„stwa.", TH: "à¸­à¸±à¸›à¹€à¸”à¸•à¸à¸²à¸£à¸•à¸±à¹‰à¸‡à¸„à¹ˆà¸²à¸šà¸±à¸à¸Šà¸µà¹à¸¥à¸°à¸£à¸²à¸¢à¸¥à¸°à¹€à¸­à¸µà¸¢à¸”à¸„à¸§à¸²à¸¡à¸›à¸¥à¸­à¸”à¸ à¸±à¸¢" },
  "Manage your personal information and account.": { PL: "ZarzÄ…dzaj danymi osobowymi i kontem.", TH: "à¸ˆà¸±à¸”à¸à¸²à¸£à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸ªà¹ˆà¸§à¸™à¸•à¸±à¸§à¹à¸¥à¸°à¸šà¸±à¸à¸Šà¸µà¸‚à¸­à¸‡à¸„à¸¸à¸“" },
  User: { PL: "UÅ¼ytkownik", TH: "à¸œà¸¹à¹‰à¹ƒà¸Šà¹‰" },
  "Member since â€”": { PL: "CzÅ‚onek od â€”", TH: "à¸ªà¸¡à¸²à¸Šà¸´à¸à¸•à¸±à¹‰à¸‡à¹à¸•à¹ˆ â€”" },
  "Member since": { PL: "CzÅ‚onek od", TH: "à¸ªà¸¡à¸²à¸Šà¸´à¸à¸•à¸±à¹‰à¸‡à¹à¸•à¹ˆ" },
  Email: { PL: "E-mail", TH: "à¸­à¸µà¹€à¸¡à¸¥" },
  "Personal Information": { PL: "Dane osobowe", TH: "à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸ªà¹ˆà¸§à¸™à¸šà¸¸à¸„à¸„à¸¥" },
  "Official account information registered on file": { PL: "Oficjalne informacje zapisane na koncie", TH: "à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸šà¸±à¸à¸Šà¸µà¸­à¸¢à¹ˆà¸²à¸‡à¹€à¸›à¹‡à¸™à¸—à¸²à¸‡à¸à¸²à¸£à¸—à¸µà¹ˆà¸¥à¸‡à¸—à¸°à¹€à¸šà¸µà¸¢à¸™à¹„à¸§à¹‰" },
  "Official cadastral identity registered on file": { PL: "Oficjalna toÅ¼samoÅ›Ä‡ katastralna zapisana w aktach", TH: "à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸•à¸±à¸§à¸•à¸™à¸—à¸µà¹ˆà¸”à¸´à¸™à¸­à¸¢à¹ˆà¸²à¸‡à¹€à¸›à¹‡à¸™à¸—à¸²à¸‡à¸à¸²à¸£à¸—à¸µà¹ˆà¸¥à¸‡à¸—à¸°à¹€à¸šà¸µà¸¢à¸™à¹„à¸§à¹‰" },
  "First name": { PL: "ImiÄ™", TH: "à¸Šà¸·à¹ˆà¸­" },
  "Last name": { PL: "Nazwisko", TH: "à¸™à¸²à¸¡à¸ªà¸à¸¸à¸¥" },
  "Mobile Number": { PL: "Numer telefonu", TH: "à¸«à¸¡à¸²à¸¢à¹€à¸¥à¸‚à¹‚à¸—à¸£à¸¨à¸±à¸žà¸—à¹Œà¸¡à¸·à¸­à¸–à¸·à¸­" },
  "Not provided": { PL: "Nie podano", TH: "à¹„à¸¡à¹ˆà¹„à¸”à¹‰à¸£à¸°à¸šà¸¸" },
  "Edit Profile â†’": { PL: "Edytuj profil â†’", TH: "à¹à¸à¹‰à¹„à¸‚à¹‚à¸›à¸£à¹„à¸Ÿà¸¥à¹Œ â†’" },
  "Edit Profile": { PL: "Edytuj profil", TH: "à¹à¸à¹‰à¹„à¸‚à¹‚à¸›à¸£à¹„à¸Ÿà¸¥à¹Œ" },
  "I agree to the": { PL: "AkceptujÄ™", TH: "à¸‰à¸±à¸™à¸¢à¸­à¸¡à¸£à¸±à¸š" },
  and: { PL: "oraz", TH: "à¹à¸¥à¸°" },
  "Please complete all required fields.": { PL: "UzupeÅ‚nij wszystkie wymagane pola.", TH: "à¸à¸£à¸¸à¸“à¸²à¸à¸£à¸­à¸à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸—à¸µà¹ˆà¸ˆà¸³à¹€à¸›à¹‡à¸™à¹ƒà¸«à¹‰à¸„à¸£à¸š" },
  "First name is required": { PL: "ImiÄ™ jest wymagane", TH: "à¸•à¹‰à¸­à¸‡à¸£à¸°à¸šà¸¸à¸Šà¸·à¹ˆà¸­" },
  "First name must be at least 2 characters": { PL: "ImiÄ™ musi mieÄ‡ co najmniej 2 znaki", TH: "à¸Šà¸·à¹ˆà¸­à¸•à¹‰à¸­à¸‡à¸¡à¸µà¸­à¸¢à¹ˆà¸²à¸‡à¸™à¹‰à¸­à¸¢ 2 à¸•à¸±à¸§à¸­à¸±à¸à¸©à¸£" },
  "Last name is required": { PL: "Nazwisko jest wymagane", TH: "à¸•à¹‰à¸­à¸‡à¸£à¸°à¸šà¸¸à¸™à¸²à¸¡à¸ªà¸à¸¸à¸¥" },
  "Last name must be at least 2 characters": { PL: "Nazwisko musi mieÄ‡ co najmniej 2 znaki", TH: "à¸™à¸²à¸¡à¸ªà¸à¸¸à¸¥à¸•à¹‰à¸­à¸‡à¸¡à¸µà¸­à¸¢à¹ˆà¸²à¸‡à¸™à¹‰à¸­à¸¢ 2 à¸•à¸±à¸§à¸­à¸±à¸à¸©à¸£" },
  "Email is required": { PL: "E-mail jest wymagany", TH: "à¸•à¹‰à¸­à¸‡à¸£à¸°à¸šà¸¸à¸­à¸µà¹€à¸¡à¸¥" },
  "Please enter a valid email address": { PL: "Podaj prawidÅ‚owy adres e-mail", TH: "à¸à¸£à¸¸à¸“à¸²à¸›à¹‰à¸­à¸™à¸­à¸µà¹€à¸¡à¸¥à¸—à¸µà¹ˆà¸–à¸¹à¸à¸•à¹‰à¸­à¸‡" },
  "Please enter a valid email address.": { PL: "Podaj prawidÅ‚owy adres e-mail.", TH: "à¸à¸£à¸¸à¸“à¸²à¸›à¹‰à¸­à¸™à¸­à¸µà¹€à¸¡à¸¥à¸—à¸µà¹ˆà¸–à¸¹à¸à¸•à¹‰à¸­à¸‡" },
  "Mobile number is required": { PL: "Numer telefonu jest wymagany", TH: "à¸•à¹‰à¸­à¸‡à¸£à¸°à¸šà¸¸à¸«à¸¡à¸²à¸¢à¹€à¸¥à¸‚à¹‚à¸—à¸£à¸¨à¸±à¸žà¸—à¹Œ" },
  "Please enter a valid mobile number": { PL: "Podaj prawidÅ‚owy numer telefonu", TH: "à¸à¸£à¸¸à¸“à¸²à¸›à¹‰à¸­à¸™à¸«à¸¡à¸²à¸¢à¹€à¸¥à¸‚à¹‚à¸—à¸£à¸¨à¸±à¸žà¸—à¹Œà¸—à¸µà¹ˆà¸–à¸¹à¸à¸•à¹‰à¸­à¸‡" },
  "Phone Number": { PL: "Numer telefonu", TH: "à¸«à¸¡à¸²à¸¢à¹€à¸¥à¸‚à¹‚à¸—à¸£à¸¨à¸±à¸žà¸—à¹Œ" },
  "Phone number is required": { PL: "Numer telefonu jest wymagany", TH: "à¸•à¹‰à¸­à¸‡à¸£à¸°à¸šà¸¸à¸«à¸¡à¸²à¸¢à¹€à¸¥à¸‚à¹‚à¸—à¸£à¸¨à¸±à¸žà¸—à¹Œ" },
  "Enter a 8-digit phone number": { PL: "Wpisz 8-cyfrowy numer telefonu", TH: "à¸›à¹‰à¸­à¸™à¸«à¸¡à¸²à¸¢à¹€à¸¥à¸‚à¹‚à¸—à¸£à¸¨à¸±à¸žà¸—à¹Œ 8 à¸«à¸¥à¸±à¸" },
  "Enter a 9-digit phone number": { PL: "Wpisz 9-cyfrowy numer telefonu", TH: "à¸›à¹‰à¸­à¸™à¸«à¸¡à¸²à¸¢à¹€à¸¥à¸‚à¹‚à¸—à¸£à¸¨à¸±à¸žà¸—à¹Œ 9 à¸«à¸¥à¸±à¸" },
  "Enter a 10-digit phone number": { PL: "Wpisz 10-cyfrowy numer telefonu", TH: "à¸›à¹‰à¸­à¸™à¸«à¸¡à¸²à¸¢à¹€à¸¥à¸‚à¹‚à¸—à¸£à¸¨à¸±à¸žà¸—à¹Œ 10 à¸«à¸¥à¸±à¸" },
  "Enter a 11-digit phone number": { PL: "Wpisz 11-cyfrowy numer telefonu", TH: "à¸›à¹‰à¸­à¸™à¸«à¸¡à¸²à¸¢à¹€à¸¥à¸‚à¹‚à¸—à¸£à¸¨à¸±à¸žà¸—à¹Œ 11 à¸«à¸¥à¸±à¸" },
  "You must agree to the Terms of Service and Privacy Policy": { PL: "Musisz zaakceptowaÄ‡ Warunki korzystania i PolitykÄ™ prywatnoÅ›ci", TH: "à¸„à¸¸à¸“à¸•à¹‰à¸­à¸‡à¸¢à¸­à¸¡à¸£à¸±à¸šà¸‚à¹‰à¸­à¸à¸³à¸«à¸™à¸”à¸à¸²à¸£à¹ƒà¸Šà¹‰à¸šà¸£à¸´à¸à¸²à¸£à¹à¸¥à¸°à¸™à¹‚à¸¢à¸šà¸²à¸¢à¸„à¸§à¸²à¸¡à¹€à¸›à¹‡à¸™à¸ªà¹ˆà¸§à¸™à¸•à¸±à¸§" },
  "You must agree to the Terms of Service and Privacy Policy.": { PL: "Musisz zaakceptowaÄ‡ Warunki korzystania i PolitykÄ™ prywatnoÅ›ci.", TH: "à¸„à¸¸à¸“à¸•à¹‰à¸­à¸‡à¸¢à¸­à¸¡à¸£à¸±à¸šà¸‚à¹‰à¸­à¸à¸³à¸«à¸™à¸”à¸à¸²à¸£à¹ƒà¸Šà¹‰à¸šà¸£à¸´à¸à¸²à¸£à¹à¸¥à¸°à¸™à¹‚à¸¢à¸šà¸²à¸¢à¸„à¸§à¸²à¸¡à¹€à¸›à¹‡à¸™à¸ªà¹ˆà¸§à¸™à¸•à¸±à¸§" },
  "Please choose an image file.": { PL: "Wybierz plik obrazu.", TH: "à¸à¸£à¸¸à¸“à¸²à¹€à¸¥à¸·à¸­à¸à¹„à¸Ÿà¸¥à¹Œà¸£à¸¹à¸›à¸ à¸²à¸ž" },
  "Profile photo must be smaller than 5 MB.": { PL: "ZdjÄ™cie profilowe musi byÄ‡ mniejsze niÅ¼ 5 MB.", TH: "à¸£à¸¹à¸›à¹‚à¸›à¸£à¹„à¸Ÿà¸¥à¹Œà¸•à¹‰à¸­à¸‡à¸¡à¸µà¸‚à¸™à¸²à¸”à¹„à¸¡à¹ˆà¹€à¸à¸´à¸™ 5 MB" },
  "Update your personal information and account.": { PL: "Zaktualizuj dane osobowe i konto.", TH: "à¸­à¸±à¸›à¹€à¸”à¸•à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸ªà¹ˆà¸§à¸™à¸•à¸±à¸§à¹à¸¥à¸°à¸šà¸±à¸à¸Šà¸µà¸‚à¸­à¸‡à¸„à¸¸à¸“" },
  "Update your password to keep your account secure.": { PL: "Zaktualizuj hasÅ‚o, aby chroniÄ‡ konto.", TH: "à¸­à¸±à¸›à¹€à¸”à¸•à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¹€à¸žà¸·à¹ˆà¸­à¸£à¸±à¸à¸©à¸²à¸„à¸§à¸²à¸¡à¸›à¸¥à¸­à¸”à¸ à¸±à¸¢à¸‚à¸­à¸‡à¸šà¸±à¸à¸Šà¸µ" },
  "Current Password": { PL: "Obecne hasÅ‚o", TH: "à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¸›à¸±à¸ˆà¸ˆà¸¸à¸šà¸±à¸™" },
  "New Password": { PL: "Nowe hasÅ‚o", TH: "à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¹ƒà¸«à¸¡à¹ˆ" },
  "Confirm Password": { PL: "PotwierdÅº hasÅ‚o", TH: "à¸¢à¸·à¸™à¸¢à¸±à¸™à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™" },
  "This field is required": { PL: "To pole jest wymagane", TH: "à¸•à¹‰à¸­à¸‡à¸£à¸°à¸šà¸¸à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸™à¸µà¹‰" },
  "Password must be at least 8 characters": { PL: "HasÅ‚o musi mieÄ‡ co najmniej 8 znakÃ³w", TH: "à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¸•à¹‰à¸­à¸‡à¸¡à¸µà¸­à¸¢à¹ˆà¸²à¸‡à¸™à¹‰à¸­à¸¢ 8 à¸•à¸±à¸§à¸­à¸±à¸à¸©à¸£" },
  "Password must contain an uppercase letter": { PL: "HasÅ‚o musi zawieraÄ‡ wielkÄ… literÄ™", TH: "à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¸•à¹‰à¸­à¸‡à¸¡à¸µà¸•à¸±à¸§à¸­à¸±à¸à¸©à¸£à¸žà¸´à¸¡à¸žà¹Œà¹ƒà¸«à¸à¹ˆ" },
  "Password must contain a lowercase letter": { PL: "HasÅ‚o musi zawieraÄ‡ maÅ‚Ä… literÄ™", TH: "à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¸•à¹‰à¸­à¸‡à¸¡à¸µà¸•à¸±à¸§à¸­à¸±à¸à¸©à¸£à¸žà¸´à¸¡à¸žà¹Œà¹€à¸¥à¹‡à¸" },
  "Password must contain a number": { PL: "HasÅ‚o musi zawieraÄ‡ cyfrÄ™", TH: "à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¸•à¹‰à¸­à¸‡à¸¡à¸µà¸•à¸±à¸§à¹€à¸¥à¸‚" },
  "Password must contain a special character": { PL: "HasÅ‚o musi zawieraÄ‡ znak specjalny", TH: "à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¸•à¹‰à¸­à¸‡à¸¡à¸µà¸­à¸±à¸à¸‚à¸£à¸°à¸žà¸´à¹€à¸¨à¸©" },
  "We couldn't update your password. Your credentials remain unchanged.": { PL: "Nie udaÅ‚o siÄ™ zaktualizowaÄ‡ hasÅ‚a. Dane logowania pozostajÄ… bez zmian.", TH: "à¹„à¸¡à¹ˆà¸ªà¸²à¸¡à¸²à¸£à¸–à¸­à¸±à¸›à¹€à¸”à¸•à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¹„à¸”à¹‰ à¸‚à¹‰à¸­à¸¡à¸¹à¸¥à¸£à¸±à¸šà¸£à¸­à¸‡à¸‚à¸­à¸‡à¸„à¸¸à¸“à¸¢à¸±à¸‡à¸„à¸‡à¹€à¸«à¸¡à¸·à¸­à¸™à¹€à¸”à¸´à¸¡" },
  "Password must be at most 100 characters": { PL: "HasÅ‚o moÅ¼e mieÄ‡ co najwyÅ¼ej 100 znakÃ³w", TH: "à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¸•à¹‰à¸­à¸‡à¸¡à¸µà¹„à¸¡à¹ˆà¹€à¸à¸´à¸™ 100 à¸•à¸±à¸§à¸­à¸±à¸à¸©à¸£" },
  "Current password is incorrect": { PL: "Obecne hasÅ‚o jest nieprawidÅ‚owe", TH: "à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¸›à¸±à¸ˆà¸ˆà¸¸à¸šà¸±à¸™à¹„à¸¡à¹ˆà¸–à¸¹à¸à¸•à¹‰à¸­à¸‡" },
  "New password must differ from current password": { PL: "Nowe hasÅ‚o musi rÃ³Å¼niÄ‡ siÄ™ od obecnego", TH: "à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¹ƒà¸«à¸¡à¹ˆà¸•à¹‰à¸­à¸‡à¹à¸•à¸à¸•à¹ˆà¸²à¸‡à¸ˆà¸²à¸à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¸›à¸±à¸ˆà¸ˆà¸¸à¸šà¸±à¸™" },
  "Password changed successfully": { PL: "HasÅ‚o zostaÅ‚o zmienione", TH: "à¹€à¸›à¸¥à¸µà¹ˆà¸¢à¸™à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¸ªà¸³à¹€à¸£à¹‡à¸ˆà¹à¸¥à¹‰à¸§" },
  "Your password has been updated successfully.": { PL: "Twoje hasÅ‚o zostaÅ‚o zaktualizowane.", TH: "à¸­à¸±à¸›à¹€à¸”à¸•à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¸‚à¸­à¸‡à¸„à¸¸à¸“à¸ªà¸³à¹€à¸£à¹‡à¸ˆà¹à¸¥à¹‰à¸§" },
  "Your session has expired. Please log in again.": { PL: "Sesja wygasÅ‚a. Zaloguj siÄ™ ponownie.", TH: "à¹€à¸‹à¸ªà¸Šà¸±à¸™à¸«à¸¡à¸”à¸­à¸²à¸¢à¸¸ à¸à¸£à¸¸à¸“à¸²à¹€à¸‚à¹‰à¸²à¸ªà¸¹à¹ˆà¸£à¸°à¸šà¸šà¸­à¸µà¸à¸„à¸£à¸±à¹‰à¸‡" },
  "Too many attempts. Please try again later.": { PL: "Zbyt wiele prÃ³b. SprÃ³buj ponownie pÃ³Åºniej.", TH: "à¸žà¸¢à¸²à¸¢à¸²à¸¡à¸«à¸¥à¸²à¸¢à¸„à¸£à¸±à¹‰à¸‡à¹€à¸à¸´à¸™à¹„à¸› à¸à¸£à¸¸à¸“à¸²à¸¥à¸­à¸‡à¹ƒà¸«à¸¡à¹ˆà¸ à¸²à¸¢à¸«à¸¥à¸±à¸‡" },
  "Unable to update your password right now. Please try again.": { PL: "Nie moÅ¼na teraz zaktualizowaÄ‡ hasÅ‚a. SprÃ³buj ponownie.", TH: "à¹„à¸¡à¹ˆà¸ªà¸²à¸¡à¸²à¸£à¸–à¸­à¸±à¸›à¹€à¸”à¸•à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¹„à¸”à¹‰à¹ƒà¸™à¸‚à¸“à¸°à¸™à¸µà¹‰ à¸à¸£à¸¸à¸“à¸²à¸¥à¸­à¸‡à¸­à¸µà¸à¸„à¸£à¸±à¹‰à¸‡" },
  Strong: { PL: "Silne", TH: "à¹à¸‚à¹‡à¸‡à¹à¸£à¸‡" },
  Average: { PL: "Åšrednie", TH: "à¸›à¸²à¸™à¸à¸¥à¸²à¸‡" },
  Weak: { PL: "SÅ‚abe", TH: "à¸­à¹ˆà¸­à¸™à¹à¸­" },
  Show: { PL: "PokaÅ¼", TH: "à¹à¸ªà¸”à¸‡" },
  Hide: { PL: "Ukryj", TH: "à¸‹à¹ˆà¸­à¸™" },
  "Passwords do not match": { PL: "HasÅ‚a nie sÄ… zgodne", TH: "à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™à¹„à¸¡à¹ˆà¸•à¸£à¸‡à¸à¸±à¸™" },
  "Confirm password is required": { PL: "Potwierdzenie hasÅ‚a jest wymagane", TH: "à¸•à¹‰à¸­à¸‡à¸¢à¸·à¸™à¸¢à¸±à¸™à¸£à¸«à¸±à¸ªà¸œà¹ˆà¸²à¸™" },
  "Something went wrong.": { PL: "CoÅ› poszÅ‚o nie tak.", TH: "à¹€à¸à¸´à¸”à¸‚à¹‰à¸­à¸œà¸´à¸”à¸žà¸¥à¸²à¸”" },
  "Try again": { PL: "SprÃ³buj ponownie", TH: "à¸¥à¸­à¸‡à¸­à¸µà¸à¸„à¸£à¸±à¹‰à¸‡" },
  "Need help? We're here for you.": { PL: "Potrzebujesz pomocy? JesteÅ›my tutaj.", TH: "à¸•à¹‰à¸­à¸‡à¸à¸²à¸£à¸„à¸§à¸²à¸¡à¸Šà¹ˆà¸§à¸¢à¹€à¸«à¸¥à¸·à¸­? à¹€à¸£à¸²à¸žà¸£à¹‰à¸­à¸¡à¸Šà¹ˆà¸§à¸¢à¸„à¸¸à¸“" },
  "Do you provide customized modular kitchens?": { PL: "Czy oferujecie niestandardowe kuchnie moduÅ‚owe?", TH: "à¸¡à¸µà¸„à¸£à¸±à¸§à¹‚à¸¡à¸”à¸¹à¸¥à¸²à¸£à¹Œà¹à¸šà¸šà¸à¸³à¸«à¸™à¸”à¹€à¸­à¸‡à¸«à¸£à¸·à¸­à¹„à¸¡à¹ˆ" },
  "Yes. Every kitchen is custom-designed to match your space, cooking habits, and style preferences.": { PL: "Tak. KaÅ¼da kuchnia jest projektowana indywidualnie do przestrzeni, nawykÃ³w i stylu.", TH: "à¹ƒà¸Šà¹ˆ à¹€à¸£à¸²à¸­à¸­à¸à¹à¸šà¸šà¸„à¸£à¸±à¸§à¹à¸•à¹ˆà¸¥à¸°à¹à¸šà¸šà¹ƒà¸«à¹‰à¹€à¸«à¸¡à¸²à¸°à¸à¸±à¸šà¸žà¸·à¹‰à¸™à¸—à¸µà¹ˆ à¸™à¸´à¸ªà¸±à¸¢à¸à¸²à¸£à¸—à¸³à¸­à¸²à¸«à¸²à¸£ à¹à¸¥à¸°à¸ªà¹„à¸•à¸¥à¹Œà¸‚à¸­à¸‡à¸„à¸¸à¸“" },
  "How do I choose a place to collect?": { PL: "Jak wybraÄ‡ miejsce do kolekcji?", TH: "à¸‰à¸±à¸™à¸ˆà¸°à¹€à¸¥à¸·à¸­à¸à¸ªà¸–à¸²à¸™à¸—à¸µà¹ˆà¸ªà¸°à¸ªà¸¡à¹„à¸”à¹‰à¸­à¸¢à¹ˆà¸²à¸‡à¹„à¸£" },
  "Explore the map, review each destination, and contact our team when you find a place that feels right.": { PL: "PrzeglÄ…daj mapÄ™, sprawdÅº miejsca i skontaktuj siÄ™ z nami, gdy znajdziesz wÅ‚aÅ›ciwe.", TH: "à¸ªà¸³à¸£à¸§à¸ˆà¹à¸œà¸™à¸—à¸µà¹ˆ à¸”à¸¹à¹à¸•à¹ˆà¸¥à¸°à¸ªà¸–à¸²à¸™à¸—à¸µà¹ˆ à¹à¸¥à¸°à¸•à¸´à¸”à¸•à¹ˆà¸­à¸—à¸µà¸¡à¸‡à¸²à¸™à¹€à¸¡à¸·à¹ˆà¸­à¸žà¸šà¸ªà¸–à¸²à¸™à¸—à¸µà¹ˆà¸—à¸µà¹ˆà¹ƒà¸Šà¹ˆ" },
  "When will I receive my certificate?": { PL: "Kiedy otrzymam certyfikat?", TH: "à¸‰à¸±à¸™à¸ˆà¸°à¹„à¸”à¹‰à¸£à¸±à¸šà¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡à¹€à¸¡à¸·à¹ˆà¸­à¹ƒà¸”" },
  "Your digital certificate is prepared after the collection details have been reviewed and confirmed.": { PL: "Certyfikat cyfrowy jest przygotowywany po sprawdzeniu i potwierdzeniu danych kolekcji.", TH: "à¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡à¸”à¸´à¸ˆà¸´à¸—à¸±à¸¥à¸ˆà¸°à¸ˆà¸±à¸”à¸—à¸³à¸«à¸¥à¸±à¸‡à¸ˆà¸²à¸à¸•à¸£à¸§à¸ˆà¸ªà¸­à¸šà¹à¸¥à¸°à¸¢à¸·à¸™à¸¢à¸±à¸™à¸£à¸²à¸¢à¸¥à¸°à¹€à¸­à¸µà¸¢à¸”à¸„à¸­à¸¥à¹€à¸¥à¸à¸Šà¸±à¸™à¹à¸¥à¹‰à¸§" },
  "Can I gift a Tajlandia collection?": { PL: "Czy mogÄ™ podarowaÄ‡ kolekcjÄ™ Tajlandia?", TH: "à¸‰à¸±à¸™à¸ªà¸²à¸¡à¸²à¸£à¸–à¸¡à¸­à¸šà¸„à¸­à¸¥à¹€à¸¥à¸à¸Šà¸±à¸™ Tajlandia à¹€à¸›à¹‡à¸™à¸‚à¸­à¸‡à¸‚à¸§à¸±à¸à¹„à¸”à¹‰à¸«à¸£à¸·à¸­à¹„à¸¡à¹ˆ" },
  "Yes. Contact support with the recipient details and our team will guide you through the gifting process.": { PL: "Tak. Podaj dane odbiorcy, a zespÃ³Å‚ przeprowadzi CiÄ™ przez proces prezentu.", TH: "à¹„à¸”à¹‰ à¸•à¸´à¸”à¸•à¹ˆà¸­à¸à¹ˆà¸²à¸¢à¸ªà¸™à¸±à¸šà¸ªà¸™à¸¸à¸™à¸žà¸£à¹‰à¸­à¸¡à¸£à¸²à¸¢à¸¥à¸°à¹€à¸­à¸µà¸¢à¸”à¸œà¸¹à¹‰à¸£à¸±à¸š à¹à¸¥à¹‰à¸§à¸—à¸µà¸¡à¸‡à¸²à¸™à¸ˆà¸°à¹à¸™à¸°à¸™à¸³à¸‚à¸±à¹‰à¸™à¸•à¸­à¸™à¸à¸²à¸£à¸¡à¸­à¸šà¸‚à¸­à¸‡à¸‚à¸§à¸±à¸" },
  "Our cadastral survey and registry team is standing by to resolve custom requests.": { PL: "ZespÃ³Å‚ pomiarÃ³w i rejestru katastralnego jest gotowy, aby zajÄ…Ä‡ siÄ™ indywidualnymi proÅ›bami.", TH: "à¸—à¸µà¸¡à¸ªà¸³à¸£à¸§à¸ˆà¹à¸¥à¸°à¸—à¸°à¹€à¸šà¸µà¸¢à¸™à¸—à¸µà¹ˆà¸”à¸´à¸™à¸žà¸£à¹‰à¸­à¸¡à¸Šà¹ˆà¸§à¸¢à¹€à¸«à¸¥à¸·à¸­à¸„à¸³à¸‚à¸­à¹€à¸‰à¸žà¸²à¸°à¸‚à¸­à¸‡à¸„à¸¸à¸“" },
  "Other": { PL: "Inne", TH: "à¸­à¸·à¹ˆà¸™à¹†" },
  "Send your Queries...": { PL: "WyÅ›lij zapytanie...", TH: "à¸ªà¹ˆà¸‡à¸„à¸³à¸–à¸²à¸¡à¸‚à¸­à¸‡à¸„à¸¸à¸“..." },
  "Please enter at least 20 words.": { PL: "Wpisz co najmniej 20 sÅ‚Ã³w.", TH: "à¸à¸£à¸¸à¸“à¸²à¸›à¹‰à¸­à¸™à¸­à¸¢à¹ˆà¸²à¸‡à¸™à¹‰à¸­à¸¢ 20 à¸„à¸³" },
  "Message sent successfully.": { PL: "WiadomoÅ›Ä‡ wysÅ‚ana pomyÅ›lnie.", TH: "à¸ªà¹ˆà¸‡à¸‚à¹‰à¸­à¸„à¸§à¸²à¸¡à¸ªà¸³à¹€à¸£à¹‡à¸ˆà¹à¸¥à¹‰à¸§" },
  "Send Message â†’": { PL: "WyÅ›lij wiadomoÅ›Ä‡ â†’", TH: "à¸ªà¹ˆà¸‡à¸‚à¹‰à¸­à¸„à¸§à¸²à¸¡ â†’" },
  "Still need help?": { PL: "Nadal potrzebujesz pomocy?", TH: "à¸¢à¸±à¸‡à¸•à¹‰à¸­à¸‡à¸à¸²à¸£à¸„à¸§à¸²à¸¡à¸Šà¹ˆà¸§à¸¢à¹€à¸«à¸¥à¸·à¸­à¸«à¸£à¸·à¸­à¹„à¸¡à¹ˆ" },
  "Within 24 hours": { PL: "W ciÄ…gu 24 godzin", TH: "à¸ à¸²à¸¢à¹ƒà¸™ 24 à¸Šà¸±à¹ˆà¸§à¹‚à¸¡à¸‡" },
  "Direct mail": { PL: "BezpoÅ›redni e-mail", TH: "à¸­à¸µà¹€à¸¡à¸¥à¹‚à¸”à¸¢à¸•à¸£à¸‡" },
  "Order #1234": { PL: "ZamÃ³wienie nr 1234", TH: "à¸„à¸³à¸ªà¸±à¹ˆà¸‡à¸‹à¸·à¹‰à¸­ #1234" },
  "Track your purchases and view your order details.": { PL: "ÅšledÅº zakupy i wyÅ›wietl szczegÃ³Å‚y zamÃ³wienia.", TH: "à¸•à¸´à¸”à¸•à¸²à¸¡à¸à¸²à¸£à¸‹à¸·à¹‰à¸­à¹à¸¥à¸°à¸”à¸¹à¸£à¸²à¸¢à¸¥à¸°à¹€à¸­à¸µà¸¢à¸”à¸„à¸³à¸ªà¸±à¹ˆà¸‡à¸‹à¸·à¹‰à¸­" },
  "Order ID": { PL: "ID zamÃ³wienia", TH: "à¸£à¸«à¸±à¸ªà¸„à¸³à¸ªà¸±à¹ˆà¸‡à¸‹à¸·à¹‰à¸­" },
  Date: { PL: "Data", TH: "à¸§à¸±à¸™à¸—à¸µà¹ˆ" },
  "Acquired Deeds": { PL: "Nabyte akty", TH: "à¹‚à¸‰à¸™à¸”à¸—à¸µà¹ˆà¹„à¸”à¹‰à¸£à¸±à¸š" },
  "Cumulative Surface": { PL: "ÅÄ…czna powierzchnia", TH: "à¸žà¸·à¹‰à¸™à¸—à¸µà¹ˆà¸ªà¸°à¸ªà¸¡" },
  "Seaview Ridge Plot": { PL: "DziaÅ‚ka Seaview Ridge", TH: "à¹à¸›à¸¥à¸‡à¸‹à¸µà¸§à¸´à¸§à¸£à¸´à¸”à¸ˆà¹Œ" },
  "Explore on Map â†—": { PL: "Eksploruj na mapie â†—", TH: "à¸ªà¸³à¸£à¸§à¸ˆà¸šà¸™à¹à¸œà¸™à¸—à¸µà¹ˆ â†—" },
  Plots: { PL: "DziaÅ‚ki", TH: "à¹à¸›à¸¥à¸‡à¸—à¸µà¹ˆà¸”à¸´à¸™" },
  "Total Rai": { PL: "ÅÄ…cznie rai", TH: "à¹„à¸£à¹ˆà¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”" },
  "Icon Zone": { PL: "Strefa Icon", TH: "à¹‚à¸‹à¸™à¹„à¸­à¸„à¸­à¸™" },
  "Popular Zone": { PL: "Strefa Popular", TH: "à¹‚à¸‹à¸™à¸¢à¸­à¸”à¸™à¸´à¸¢à¸¡" },
  "Standard Zone": { PL: "Strefa Standard", TH: "à¹‚à¸‹à¸™à¸¡à¸²à¸•andardowa" },
  Subtotal: { PL: "Suma czÄ™Å›ciowa", TH: "à¸¢à¸­à¸”à¸£à¸§à¸¡à¸¢à¹ˆà¸­à¸¢" },
  Total: { PL: "Razem", TH: "à¸£à¸§à¸¡" },
  Paid: { PL: "OpÅ‚acono", TH: "à¸Šà¸³à¸£à¸°à¹à¸¥à¹‰à¸§" },
  "Search Maps": { PL: "Szukaj na mapie", TH: "à¸„à¹‰à¸™à¸«à¸²à¹à¸œà¸™à¸—à¸µà¹ˆ" },
  "Clear search": { PL: "WyczyÅ›Ä‡ wyszukiwanie", TH: "à¸¥à¹‰à¸²à¸‡à¸à¸²à¸£à¸„à¹‰à¸™à¸«à¸²" },
  "Plot Status": { PL: "Status dziaÅ‚ki", TH: "à¸ªà¸–à¸²à¸™à¸°à¹à¸›à¸¥à¸‡à¸—à¸µà¹ˆà¸”à¸´à¸™" },
  Locked: { PL: "Zablokowane", TH: "à¸¥à¹‡à¸­à¸à¹à¸¥à¹‰à¸§" },
  Taken: { PL: "ZajÄ™te", TH: "à¸–à¸¹à¸à¸ˆà¸­à¸‡à¹à¸¥à¹‰à¸§" },
  "Your plots": { PL: "Twoje dziaÅ‚ki", TH: "à¹à¸›à¸¥à¸‡à¸‚à¸­à¸‡à¸„à¸¸à¸“" },
  "All plots": { PL: "Wszystkie dziaÅ‚ki", TH: "à¹à¸›à¸¥à¸‡à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”" },
  "Recently viewed": { PL: "Ostatnio oglÄ…dane", TH: "à¸”à¸¹à¸¥à¹ˆà¸²à¸ªà¸¸à¸”" },
  Name: { PL: "Nazwa", TH: "à¸Šà¸·à¹ˆà¸­" },
  "Most locations": { PL: "NajwiÄ™cej lokalizacji", TH: "à¸ªà¸–à¸²à¸™à¸—à¸µà¹ˆà¸¡à¸²à¸à¸—à¸µà¹ˆà¸ªà¸¸à¸”" },
  "No places match your search.": { PL: "Brak miejsc pasujÄ…cych do wyszukiwania.", TH: "à¹„à¸¡à¹ˆà¸žà¸šà¸ªà¸–à¸²à¸™à¸—à¸µà¹ˆà¸—à¸µà¹ˆà¸•à¸£à¸‡à¸à¸±à¸šà¸à¸²à¸£à¸„à¹‰à¸™à¸«à¸²" },
  "Show less": { PL: "PokaÅ¼ mniej", TH: "à¹à¸ªà¸”à¸‡à¸™à¹‰à¸­à¸¢à¸¥à¸‡" },
  "More from recent history": { PL: "WiÄ™cej z ostatniej historii", TH: "à¹€à¸žà¸´à¹ˆà¸¡à¹€à¸•à¸´à¸¡à¸ˆà¸²à¸à¸›à¸£à¸°à¸§à¸±à¸•à¸´à¸¥à¹ˆà¸²à¸ªà¸¸à¸”" },
  "Current location": { PL: "BieÅ¼Ä…ca lokalizacja", TH: "à¸•à¸³à¹à¸«à¸™à¹ˆà¸‡à¸›à¸±à¸ˆà¸ˆà¸¸à¸šà¸±à¸™" },
  "Zoom in": { PL: "PowiÄ™ksz", TH: "à¸‹à¸¹à¸¡à¹€à¸‚à¹‰à¸²" },
  "Zoom out": { PL: "Pomniejsz", TH: "à¸‹à¸¹à¸¡à¸­à¸­à¸" },
  "Selected Plots": { PL: "Wybrane dziaÅ‚ki", TH: "à¹à¸›à¸¥à¸‡à¸—à¸µà¹ˆà¹€à¸¥à¸·à¸­à¸" },
  "Your Cart": { PL: "TwÃ³j koszyk", TH: "à¸£à¸–à¹€à¸‚à¹‡à¸™à¸‚à¸­à¸‡à¸„à¸¸à¸“" },
  "Review your selected plots before checkout.": {
    PL: "SprawdÅº wybrane dziaÅ‚ki przed pÅ‚atnoÅ›ciÄ….",
    TH: "à¸•à¸£à¸§à¸ˆà¸ªà¸­à¸šà¹à¸›à¸¥à¸‡à¸—à¸µà¹ˆà¹€à¸¥à¸·à¸­à¸à¸à¹ˆà¸­à¸™à¸Šà¸³à¸£à¸°à¹€à¸‡à¸´à¸™",
  },
  "Add more plots and make them yours.": {
    PL: "Dodaj wiÄ™cej dziaÅ‚ek i uczyÅ„ je swoimi.",
    TH: "à¹€à¸žà¸´à¹ˆà¸¡à¹à¸›à¸¥à¸‡à¸­à¸µà¸à¹à¸¥à¸°à¸—à¸³à¹ƒà¸«à¹‰à¹€à¸›à¹‡à¸™à¸‚à¸­à¸‡à¸„à¸¸à¸“",
  },
  "Unlock deed certification and blockchain cadastral inscription by selecting 25 additional Rai.": {
    PL: "Odblokuj certyfikacjÄ™ aktu i wpis katastralny, wybierajÄ…c dodatkowe 25 Rai.",
    TH: "à¸›à¸¥à¸”à¸¥à¹‡à¸­à¸à¸à¸²à¸£à¸£à¸±à¸šà¸£à¸­à¸‡à¹‚à¸‰à¸™à¸”à¹à¸¥à¸°à¸à¸²à¸£à¸ˆà¸”à¸—à¸°à¹€à¸šà¸µà¸¢à¸™à¸—à¸µà¹ˆà¸”à¸´à¸™à¸”à¹‰à¸§à¸¢à¸à¸²à¸£à¹€à¸¥à¸·à¸­à¸à¹€à¸žà¸´à¹ˆà¸¡à¸­à¸µà¸ 25 à¹„à¸£à¹ˆ",
  },
  "Minimum purchase reached": { PL: "OsiÄ…gniÄ™to minimalny zakup", TH: "à¸–à¸¶à¸‡à¸¢à¸­à¸”à¸‹à¸·à¹‰à¸­à¸‚à¸±à¹‰à¸™à¸•à¹ˆà¸³à¹à¸¥à¹‰à¸§" },
  "Your selection meets the 100 Rai minimum.": {
    PL: "TwÃ³j wybÃ³r speÅ‚nia minimum 100 Rai.",
    TH: "à¸£à¸²à¸¢à¸à¸²à¸£à¸—à¸µà¹ˆà¸„à¸¸à¸“à¹€à¸¥à¸·à¸­à¸à¸–à¸¶à¸‡à¸‚à¸±à¹‰à¸™à¸•à¹ˆà¸³ 100 à¹„à¸£à¹ˆà¹à¸¥à¹‰à¸§",
  },
  "Proceed to checkout â†’": { PL: "PrzejdÅº do pÅ‚atnoÅ›ci â†’", TH: "à¹„à¸›à¸—à¸µà¹ˆà¸Šà¸³à¸£à¸°à¹€à¸‡à¸´à¸™ â†’" },
  "Continue Exploring": { PL: "Kontynuuj odkrywanie", TH: "à¸ªà¸³à¸£à¸§à¸ˆà¸•à¹ˆà¸­" },
  "Loading cart...": { PL: "Åadowanie koszyka...", TH: "à¸à¸³à¸¥à¸±à¸‡à¹‚à¸«à¸¥à¸”à¸£à¸–à¹€à¸‚à¹‡à¸™..." },
  "Enter Code": { PL: "Wpisz kod", TH: "à¸›à¹‰à¸­à¸™à¸£à¸«à¸±à¸ª" },
  "Certificate PDF": { PL: "PDF certyfikatu", TH: "PDF à¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡" },
  "Certificate ID": { PL: "ID certyfikatu", TH: "à¸£à¸«à¸±à¸ªà¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡" },
  "Registered Owner": { PL: "Zarejestrowany wÅ‚aÅ›ciciel", TH: "à¹€à¸ˆà¹‰à¸²à¸‚à¸­à¸‡à¸—à¸µà¹ˆà¸¥à¸‡à¸—à¸°à¹€à¸šà¸µà¸¢à¸™" },
  "Total Area": { PL: "ÅÄ…czna powierzchnia", TH: "à¸žà¸·à¹‰à¸™à¸—à¸µà¹ˆà¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”" },
  "Plots Count": { PL: "Liczba dziaÅ‚ek", TH: "à¸ˆà¸³à¸™à¸§à¸™à¹à¸›à¸¥à¸‡" },
  "Issuing Authority": { PL: "Organ wydajÄ…cy", TH: "à¸«à¸™à¹ˆà¸§à¸¢à¸‡à¸²à¸™à¸œà¸¹à¹‰à¸­à¸­à¸" },
  "Issue Date": { PL: "Data wydania", TH: "à¸§à¸±à¸™à¸—à¸µà¹ˆà¸­à¸­à¸" },
  "Copy link": { PL: "Kopiuj link", TH: "à¸„à¸±à¸”à¸¥à¸­à¸à¸¥à¸´à¸‡à¸à¹Œ" },
  Copied: { PL: "Skopiowano", TH: "à¸„à¸±à¸”à¸¥à¸­à¸à¹à¸¥à¹‰à¸§" },
  "Curated by newly added": { PL: "Wybrane wedÅ‚ug najnowszych", TH: "à¸„à¸±à¸”à¸ªà¸£à¸£à¸ˆà¸²à¸à¸£à¸²à¸¢à¸à¸²à¸£à¹ƒà¸«à¸¡à¹ˆ" },
  "Date: Old to New": { PL: "Data: od najstarszej", TH: "à¸§à¸±à¸™à¸—à¸µà¹ˆ: à¹€à¸à¹ˆà¸²à¹„à¸›à¹ƒà¸«à¸¡à¹ˆ" },
  "Date: New to Old": { PL: "Data: od najnowszej", TH: "à¸§à¸±à¸™à¸—à¸µà¹ˆ: à¹ƒà¸«à¸¡à¹ˆà¹„à¸›à¹€à¸à¹ˆà¸²" },
  "Certificate ID (A-Z)": { PL: "ID certyfikatu (A-Z)", TH: "à¸£à¸«à¸±à¸ªà¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡ (A-Z)" },
  "Certificate ID (Z-A)": { PL: "ID certyfikatu (Z-A)", TH: "à¸£à¸«à¸±à¸ªà¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡ (Z-A)" },
  "My Plots": { PL: "Moje dziaÅ‚ki", TH: "à¹à¸›à¸¥à¸‡à¸‚à¸­à¸‡à¸‰à¸±à¸™" },
  Icon: { PL: "Icon", TH: "à¹„à¸­à¸„à¸­à¸™" },
  "77 plots found": { PL: "Znaleziono 77 dziaÅ‚ek", TH: "à¸žà¸š 77 à¹à¸›à¸¥à¸‡" },
  "Certificates found": { PL: "Znaleziono certyfikaty", TH: "à¸žà¸šà¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡" },
  "0 certificates found": { PL: "Nie znaleziono certyfikatÃ³w", TH: "à¹„à¸¡à¹ˆà¸žà¸šà¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡" },
  Area: { PL: "Powierzchnia", TH: "à¸žà¸·à¹‰à¸™à¸—à¸µà¹ˆ" },
  Rate: { PL: "Stawka", TH: "à¸­à¸±à¸•à¸£à¸²" },
  "Amt Paid": { PL: "ZapÅ‚acono", TH: "à¸¢à¸­à¸”à¸Šà¸³à¸£à¸°" },
  "NEXT STEP:": { PL: "NASTÄ˜PNY KROK:", TH: "à¸‚à¸±à¹‰à¸™à¸•à¸­à¸™à¸–à¸±à¸”à¹„à¸›:" },
  "Select parcels from any": { PL: "Wybierz dziaÅ‚ki z dowolnego", TH: "à¹€à¸¥à¸·à¸­à¸à¹à¸›à¸¥à¸‡à¸ˆà¸²à¸" },
  "All changes verified under 256-bit Cadastral Escrow protocol.": { PL: "Wszystkie zmiany zweryfikowane w protokole Cadastral Escrow 256-bit.", TH: "à¸•à¸£à¸§à¸ˆà¸ªà¸­à¸šà¸à¸²à¸£à¹€à¸›à¸¥à¸µà¹ˆà¸¢à¸™à¹à¸›à¸¥à¸‡à¸—à¸±à¹‰à¸‡à¸«à¸¡à¸”à¸ à¸²à¸¢à¹ƒà¸•à¹‰à¹‚à¸›à¸£à¹‚à¸•à¸„à¸­à¸¥ Cadastral Escrow 256 à¸šà¸´à¸•à¹à¸¥à¹‰à¸§" },
  "Save Changes": { PL: "Zapisz zmiany", TH: "à¸šà¸±à¸™à¸—à¸¶à¸à¸à¸²à¸£à¹€à¸›à¸¥à¸µà¹ˆà¸¢à¸™à¹à¸›à¸¥à¸‡" },
  Discard: { PL: "OdrzuÄ‡", TH: "à¸¢à¸à¹€à¸¥à¸´à¸" },
  "Change Photo": { PL: "ZmieÅ„ zdjÄ™cie", TH: "à¹€à¸›à¸¥à¸µà¹ˆà¸¢à¸™à¸£à¸¹à¸›à¸ à¸²à¸ž" },
  "Add Photo": { PL: "Dodaj zdjÄ™cie", TH: "à¹€à¸žà¸´à¹ˆà¸¡à¸£à¸¹à¸›à¸ à¸²à¸ž" },
  "Terms of Service": { PL: "Warunki korzystania", TH: "à¸‚à¹‰à¸­à¸à¸³à¸«à¸™à¸”à¸à¸²à¸£à¹ƒà¸Šà¹‰à¸šà¸£à¸´à¸à¸²à¸£" },
  "Profile updated successfully.": { PL: "Profil zaktualizowany pomyÅ›lnie.", TH: "à¸­à¸±à¸›à¹€à¸”à¸•à¹‚à¸›à¸£à¹„à¸Ÿà¸¥à¹Œà¸ªà¸³à¹€à¸£à¹‡à¸ˆà¹à¸¥à¹‰à¸§" },
  "Your profile has been saved successfully.": { PL: "TwÃ³j profil zostaÅ‚ zapisany.", TH: "à¸šà¸±à¸™à¸—à¸¶à¸à¹‚à¸›à¸£à¹„à¸Ÿà¸¥à¹Œà¸‚à¸­à¸‡à¸„à¸¸à¸“à¸ªà¸³à¹€à¸£à¹‡à¸ˆà¹à¸¥à¹‰à¸§" },
  Okay: { PL: "OK", TH: "à¸•à¸à¸¥à¸‡" },
  "Total:": { PL: "Razem:", TH: "à¸£à¸§à¸¡:" },
  "NEXT STEP: Select parcels from any": { PL: "NASTÄ˜PNY KROK: Wybierz dziaÅ‚ki z dowolnego", TH: "à¸‚à¸±à¹‰à¸™à¸•à¸­à¸™à¸–à¸±à¸”à¹„à¸›: à¹€à¸¥à¸·à¸­à¸à¹à¸›à¸¥à¸‡à¸ˆà¸²à¸" },
  "Remove": { PL: "UsuÅ„", TH: "à¸¥à¸š" },
  "Tajlandia Certificate": { PL: "Certyfikat Tajlandia", TH: "à¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡ Tajlandia" },
  "Share certificate": { PL: "UdostÄ™pnij certyfikat", TH: "à¹à¸Šà¸£à¹Œà¹ƒà¸šà¸£à¸±à¸šà¸£à¸­à¸‡" },
  "Share order": { PL: "UdostÄ™pnij zamÃ³wienie", TH: "à¹à¸Šà¸£à¹Œà¸„à¸³à¸ªà¸±à¹ˆà¸‡à¸‹à¸·à¹‰à¸­" },
};

type DashboardLanguageContextValue = {
  language: DashboardLanguage;
  setLanguage: (language: DashboardLanguage) => void;
  t: (source: string) => string;
};

const DashboardLanguageContext = createContext<DashboardLanguageContextValue | null>(
  null,
);

export function DashboardLanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<DashboardLanguage>("EN");
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    const stored = window.localStorage.getItem("tajlandia_dashboard_language");
    if (stored === "EN" || stored === "PL" || stored === "TH") setLanguageState(stored);
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated) return;
    window.localStorage.setItem("tajlandia_dashboard_language", language);
    document.documentElement.lang = language === "TH" ? "th" : language === "PL" ? "pl" : "en";
  }, [hydrated, language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage: (nextLanguage: DashboardLanguage) => setLanguageState(nextLanguage),
      t: (source: string) => language === "EN" ? source : translations[source]?.[language] ?? source,
    }),
    [language],
  );

  return (
    <DashboardLanguageContext.Provider value={value}>{children}</DashboardLanguageContext.Provider>
  );
}

export function useDashboardLanguage() {
  const context = useContext(DashboardLanguageContext);
  if (!context)
    throw new Error("useDashboardLanguage must be used within DashboardLanguageProvider");
  return context;
}

export function useOptionalDashboardLanguage() {
  const context = useContext(DashboardLanguageContext);
  return context ?? {
    language: "EN" as const,
    setLanguage: () => undefined,
    t: (source: string) => source,
  };
}
